### ISSUE TITLE
adb device couldn't get wifi mac.

### ISSUE THREAD

**Issue by anonymous-qsh** [4ch12dy/xadb#1]
当我使用adb device 不能获取正确的mac 地址, 输出如下

```
cat: /sys/class/net/wlan0/address: Permission denied
model                Nexus 5X
brand                google
manufacturer         LGE
abilist              arm64-v8a,armeabi-v7a,armeabi
sdk                  27
wifi ipv4            192.168.0.103
wifi mac
os version           8.1.0
serialno           xxx
imei                 xxxxx
android_id           xxxxxxx
can debug?           0
```

初步判断是由于` adb shell cat /sys/class/net/wlan0/address`报错

我替换为`adb shell ip address show wlan0 | grep "link/ether" | awk '{printf $2}'`, 之后可以正常获取.

参考: https://android.stackexchange.com/questions/142606/how-can-i-find-my-mac-address

**Comment by 4ch12dy** [comment]
多谢，如果普遍存在这个问题的话，我就把mac地址的获取方式改你提供的那种。之前测试的Nexus和pixel机型没遇到这个问题，你的设备root了吗？

**Comment by anonymous-qsh** [comment]
我设备root了.

**Comment by 4ch12dy** [comment]
你执行下`adb sudo "cat /sys/class/net/wlan0/address"`能成功获取到mac吗？

**Comment by anonymous-qsh** [comment]
可以成功获取到.

**Comment by 4ch12dy** [comment]
那应该就权限问题，我改下代码，如果这种获取的时候有权限问题就用上面那种

**Comment by anonymous-qsh** [comment]
嗯嗯 谢谢作者了
